version: '3'

services:
  app:
    build: .
    ports: 
      - "8080"
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client 0.0.0.0"
  lb:
    image: haproxy
    volumes:
      - ./configs/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"