version: '3'

services:
  app:
    build: .
    ports: 
      - "8080"
  consul:
    image: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client 0.0.0.0"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - "9090:9090"